
[general]
import = [
    "~/.config/alacritty/themes/themes/terafox.toml"
]

[font]
size = 12
normal = { family = "JetBrainsMono NF" }

[window]
padding = { x = 4, y = 4 }
startup_mode = "Maximized"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullScreen" }]
